<?php

declare(strict_types=1);

namespace Tests\Feature\Housing;

use App\Enums\AuditAction;
use App\Enums\Citizenship;
use App\Enums\RoleCode;
use App\Models\AuditLog;
use App\Models\Building;
use App\Models\User;
use Database\Seeders\RoleSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Notification;
use Illuminate\Support\Facades\Queue;
use Laravel\Sanctum\Sanctum;
use Tests\TestCase;

/**
 * FR-42, «Issuing a resident account».
 *
 * The MVP hands the password over on paper. The server generates one, stores
 * its hash and returns the plain text once, in the answer to the request that
 * created the account; the office prints that answer and gives it to the person
 * it belongs to. Nothing is sent anywhere, so there is no mail server in the
 * scenario and no one-time code to expire.
 *
 * That makes «the password is readable exactly once» the claim worth testing
 * carefully, and it is two claims: the creating response carries it, and no
 * other road out of the application does — not a second read of the account,
 * not the queue, not the audit log.
 */
final class ResidentAccountTest extends TestCase
{
    use RefreshDatabase;

    private Building $first;

    private Building $second;

    private User $managerOfFirst;

    protected function setUp(): void
    {
        parent::setUp();

        $this->seed(RoleSeeder::class);

        $this->first = Building::factory()->create(['name' => 'Block 1']);
        $this->second = Building::factory()->create(['name' => 'Block 2']);

        $this->managerOfFirst = User::factory()
            ->withRole(RoleCode::Manager, $this->first)
            ->create(['email' => 'manager-of-first@example.test']);
    }

    /**
     * First and second criteria: the manager of a building creates an account
     * for an incoming resident of that building, and the grant it carries is
     * the resident role scoped to it.
     */
    public function test_the_manager_creates_an_account_for_an_incoming_resident_of_their_own_building(): void
    {
        Sanctum::actingAs($this->managerOfFirst);

        $response = $this->postJson("/api/v1/buildings/{$this->first->id}/residents", $this->payload([
            'full_name' => 'Taisiya Kurbatova',
            'email' => 'incoming@example.test',
        ]))->assertStatus(201);

        $resident = User::query()->where('email', 'incoming@example.test')->sole();

        $response
            ->assertJsonPath('data.user.id', $resident->id)
            ->assertJsonPath('data.user.full_name', 'Taisiya Kurbatova')
            ->assertJsonPath('data.user.phone', '+79001112233')
            ->assertJsonPath('data.user.password_change_required', true)
            ->assertJsonPath('data.user.roles.0.role', 'student')
            ->assertJsonPath('data.user.roles.0.building_id', $this->first->id)
            ->assertJsonPath('data.building.id', $this->first->id)
            ->assertJsonPath('data.building.name', 'Block 1');

        $this->assertSame(Citizenship::Russia, $resident->citizenship);
    }

    /**
     * Revision 2 of the role model leaves the warden every capability the
     * manager has, this one included.
     */
    public function test_the_warden_creates_an_account_as_well(): void
    {
        $warden = User::factory()
            ->withRole(RoleCode::Warden, $this->first)
            ->create(['email' => 'warden-of-first@example.test']);

        Sanctum::actingAs($warden);

        $this->postJson("/api/v1/buildings/{$this->first->id}/residents", $this->payload([
            'full_name' => 'Gleb Shilov',
            'email' => 'wardens-resident@example.test',
        ]))->assertStatus(201);

        $resident = User::query()->where('email', 'wardens-resident@example.test')->sole();

        $this->assertTrue($resident->hasRoleInBuilding(RoleCode::Resident, $this->first));
    }

    /**
     * Third criterion: the password is generated by the server, returned once,
     * and it works.
     */
    public function test_the_generated_password_comes_back_once_and_signs_the_resident_in(): void
    {
        Sanctum::actingAs($this->managerOfFirst);

        $response = $this->postJson("/api/v1/buildings/{$this->first->id}/residents", $this->payload([
            'full_name' => 'Milana Panfilova',
            'email' => 'handed-over@example.test',
        ]))->assertStatus(201);

        $password = $response->json('data.password');

        $this->assertIsString($password);
        $this->assertNotSame('', $password);

        $resident = User::query()->where('email', 'handed-over@example.test')->sole();

        // The table holds a hash and never the text that was handed over.
        $this->assertNotSame($password, $resident->getAttributes()['password_hash']);

        $this->postJson('/api/v1/auth/login', [
            'email' => 'handed-over@example.test',
            'password' => $password,
        ])
            ->assertOk()
            ->assertJsonPath('data.user.password_change_required', true);
    }

    /**
     * The other half of «once»: no later read of the account carries the
     * password, and neither does the queue.
     *
     * The assertion walks the whole body rather than naming a field, so a
     * secret added under a different name fails it too.
     */
    public function test_no_second_road_carries_the_password_out_of_the_application(): void
    {
        Queue::fake();
        Notification::fake();

        Sanctum::actingAs($this->managerOfFirst);

        $this->postJson("/api/v1/buildings/{$this->first->id}/residents", $this->payload([
            'full_name' => 'Savva Yakimov',
            'email' => 'no-second-road@example.test',
        ]))->assertStatus(201);

        // Nothing was queued and nothing was sent: the credential does not
        // leave the application at all.
        Queue::assertNothingPushed();
        Notification::assertNothingSent();

        // And reading the account back — the card is the fullest answer the
        // system gives about a person — carries no secret at any depth.
        $resident = User::query()->where('email', 'no-second-road@example.test')->sole();

        $card = $this->getJson("/api/v1/residents/{$resident->id}")->assertOk();

        $this->assertNoSecretIn($card->json());
    }

    /**
     * Fourth criterion: «creating an account for another building is refused».
     */
    public function test_creating_a_resident_in_another_building_is_refused(): void
    {
        Sanctum::actingAs($this->managerOfFirst);

        $this->postJson("/api/v1/buildings/{$this->second->id}/residents", $this->payload([
            'full_name' => 'Rostislav Tregubov',
            'email' => 'elsewhere@example.test',
        ]))->assertStatus(403);

        $this->assertFalse(User::query()->where('email', 'elsewhere@example.test')->exists());
    }

    /**
     * Second criterion: «no staff role can be issued this way». There is no
     * parameter for one, and a payload that invents it changes nothing.
     */
    public function test_no_staff_role_can_be_issued_through_this_route(): void
    {
        Sanctum::actingAs($this->managerOfFirst);

        $this->postJson("/api/v1/buildings/{$this->first->id}/residents", $this->payload([
            'full_name' => 'Vera Zheltova',
            'email' => 'not-staff@example.test',
            'role' => RoleCode::Warden->value,
        ]))->assertStatus(201);

        $resident = User::query()->where('email', 'not-staff@example.test')->sole();

        $this->assertSame(1, $resident->roleGrants()->count());
        $this->assertTrue($resident->hasRoleInBuilding(RoleCode::Resident, $this->first));
        $this->assertFalse($resident->hasRoleInBuilding(RoleCode::Warden, $this->first));
    }

    /**
     * And a payload that invents a password changes nothing either: the server
     * generates one, so there is no field through which a chosen one could be
     * smuggled in.
     */
    public function test_a_password_in_the_payload_is_not_the_password_of_the_account(): void
    {
        Sanctum::actingAs($this->managerOfFirst);

        $response = $this->postJson("/api/v1/buildings/{$this->first->id}/residents", $this->payload([
            'full_name' => 'Nikita Zheltov',
            'email' => 'chosen-password@example.test',
            'password' => 'letmein',
        ]))->assertStatus(201);

        $this->assertNotSame('letmein', $response->json('data.password'));

        $this->postJson('/api/v1/auth/login', [
            'email' => 'chosen-password@example.test',
            'password' => 'letmein',
        ])->assertStatus(401);
    }

    public function test_a_resident_issues_no_account_and_neither_does_a_security_officer(): void
    {
        foreach ([RoleCode::Resident, RoleCode::SecurityOfficer] as $index => $role) {
            $user = User::factory()
                ->withRole($role, $this->first)
                ->create(['email' => sprintf('outsider-%d@example.test', $index)]);

            Sanctum::actingAs($user);

            $this->postJson("/api/v1/buildings/{$this->first->id}/residents", $this->payload([
                'full_name' => 'Nikita Zheltov',
                'email' => sprintf('refused-%d@example.test', $index),
            ]))->assertStatus(403);
        }
    }

    public function test_an_address_already_in_use_is_a_malformed_request(): void
    {
        Sanctum::actingAs($this->managerOfFirst);

        $this->postJson("/api/v1/buildings/{$this->first->id}/residents", $this->payload([
            'full_name' => 'Duplicate Person',
            'email' => $this->managerOfFirst->email,
        ]))
            ->assertStatus(422)
            ->assertJsonValidationErrors('email');
    }

    /**
     * The office rings the resident, so an account with no number is an
     * account nobody can reach. There is no confirmation of the number and no
     * state in which it is missing.
     */
    public function test_the_telephone_number_is_required(): void
    {
        Sanctum::actingAs($this->managerOfFirst);

        $this->postJson("/api/v1/buildings/{$this->first->id}/residents", [
            'full_name' => 'No Telephone',
            'email' => 'no-phone@example.test',
            'citizenship' => Citizenship::Russia->value,
        ])
            ->assertStatus(422)
            ->assertJsonValidationErrors('phone');
    }

    /**
     * Citizenship is a closed list, so that «RU», «Россия» and «russian» are
     * not three citizenships.
     */
    public function test_the_citizenship_comes_from_the_closed_list(): void
    {
        Sanctum::actingAs($this->managerOfFirst);

        $this->postJson("/api/v1/buildings/{$this->first->id}/residents", $this->payload([
            'full_name' => 'Free Text',
            'email' => 'free-text@example.test',
            'citizenship' => 'Russia',
        ]))
            ->assertStatus(422)
            ->assertJsonValidationErrors('citizenship');

        $this->postJson("/api/v1/buildings/{$this->first->id}/residents", [
            'full_name' => 'No Citizenship',
            'email' => 'no-citizenship@example.test',
            'phone' => '+79001112233',
        ])
            ->assertStatus(422)
            ->assertJsonValidationErrors('citizenship');
    }

    /**
     * And the client is told the list rather than left to guess it, so the
     * dropdown and the rule read the same source.
     */
    public function test_the_list_of_citizenships_is_published_for_the_form(): void
    {
        Sanctum::actingAs($this->managerOfFirst);

        $response = $this->getJson('/api/v1/citizenships')->assertOk();

        $values = collect($response->json('data'))->pluck('value')->all();

        $this->assertSame(Citizenship::values(), $values);
        $this->assertContains('Russia', collect($response->json('data'))->pluck('label')->all());
    }

    /**
     * FR-33: the issue is an event. What it records is that an account was
     * created, by whom and where — never the password it was created with.
     */
    public function test_issuing_an_account_is_written_to_the_audit_log_without_the_password(): void
    {
        Sanctum::actingAs($this->managerOfFirst);

        $response = $this->postJson("/api/v1/buildings/{$this->first->id}/residents", $this->payload([
            'full_name' => 'Yulia Panfilova',
            'email' => 'audited-resident@example.test',
        ]))->assertStatus(201);

        $resident = User::query()->where('email', 'audited-resident@example.test')->sole();

        $entry = AuditLog::query()
            ->where('action', AuditAction::ResidentAccountIssued->value)
            ->sole();

        $this->assertSame($this->managerOfFirst->id, $entry->user_id);
        $this->assertSame($resident->id, $entry->subject_id);
        $this->assertSame($this->first->id, $entry->payload['building_id']);
        $this->assertSame('student', $entry->payload['role']);
        $this->assertNoSecretIn($entry->payload);

        $this->assertStringNotContainsString(
            (string) $response->json('data.password'),
            (string) json_encode($entry->payload),
        );
    }

    /**
     * FR-42, the resident's end of it: they sign in with what the office gave
     * them and put a password of their own in its place. The flag clears with
     * the change, and every session the account held is revoked — the one
     * making the change included.
     */
    public function test_the_resident_replaces_the_issued_password_with_one_of_their_own(): void
    {
        $resident = User::factory()
            ->withPassword('handed-over-on-paper')
            ->withRole(RoleCode::Resident, $this->first)
            ->create([
                'email' => 'changing@example.test',
                'password_change_required' => true,
            ]);

        Sanctum::actingAs($resident);

        $this->postJson('/api/v1/auth/password', [
            'current_password' => 'handed-over-on-paper',
            'password' => 'a-password-of-my-own',
            'password_confirmation' => 'a-password-of-my-own',
        ])->assertStatus(204);

        $this->assertFalse($resident->fresh()->password_change_required);
        $this->assertSame(0, $resident->tokens()->count());

        $this->postJson('/api/v1/auth/login', [
            'email' => 'changing@example.test',
            'password' => 'a-password-of-my-own',
        ])
            ->assertOk()
            ->assertJsonPath('data.user.password_change_required', false);

        $entry = AuditLog::query()
            ->where('action', AuditAction::PasswordSet->value)
            ->sole();

        $this->assertSame($resident->id, $entry->user_id);
        $this->assertNoSecretIn($entry->payload ?? []);
    }

    /**
     * A stolen session is not a stolen account: the password that is being
     * replaced has to be presented with the replacement.
     */
    public function test_the_old_password_is_required_to_set_a_new_one(): void
    {
        $resident = User::factory()
            ->withPassword('handed-over-on-paper')
            ->withRole(RoleCode::Resident, $this->first)
            ->create(['email' => 'thief@example.test', 'password_change_required' => true]);

        Sanctum::actingAs($resident);

        $this->postJson('/api/v1/auth/password', [
            'current_password' => 'a-guess',
            'password' => 'taken-over',
            'password_confirmation' => 'taken-over',
        ])
            ->assertStatus(422)
            ->assertJsonValidationErrors('current_password');

        $this->assertTrue($resident->fresh()->password_change_required);
    }

    public function test_nobody_changes_a_password_without_a_session(): void
    {
        $this->postJson('/api/v1/auth/password', [
            'current_password' => 'whatever',
            'password' => 'a-password-of-my-own',
            'password_confirmation' => 'a-password-of-my-own',
        ])->assertStatus(401);
    }

    /**
     * The fields every valid call carries, so that a test about one of them
     * does not have to restate the other three.
     *
     * @param  array<string, mixed>  $overrides
     * @return array<string, mixed>
     */
    private function payload(array $overrides = []): array
    {
        return $overrides + [
            'phone' => '+79001112233',
            'citizenship' => Citizenship::Russia->value,
        ];
    }

    /**
     * No field anywhere in the structure carries a secret, at any depth.
     *
     * The list is of names a secret could plausibly travel under rather than
     * of the one name it travels under today, so a future field called
     * `temporary_password` fails this assertion on the day it is added.
     * `password_change_required` is deliberately not among them: it says an
     * account still owes a change and carries no secret.
     *
     * @param  mixed  $value
     */
    private function assertNoSecretIn($value, string $path = 'root'): void
    {
        $secretNames = [
            'password', 'password_hash', 'plain_password', 'plain_text_password',
            'temporary_password', 'one_time_password', 'initial_password',
            'secret', 'credential', 'credentials', 'token', 'reset_token',
        ];

        if (! is_array($value)) {
            return;
        }

        foreach ($value as $key => $nested) {
            if (is_string($key)) {
                $this->assertNotContains(
                    strtolower($key),
                    $secretNames,
                    sprintf('A secret travels in the answer, at %s.%s.', $path, $key),
                );
            }

            $this->assertNoSecretIn($nested, $path.'.'.$key);
        }
    }
}
