<?php

declare(strict_types=1);

namespace App\Http\Requests\Api\V1;

use App\Enums\Citizenship;
use App\Models\Building;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

/**
 * FR-42: `POST /api/v1/buildings/{building}/residents`.
 *
 * The building comes from the path, so «their own building» is decided on the
 * object the route named and a request against another dormitory is refused
 * here, before a row is written.
 *
 * There is no `role` field and no `password` field. The role is fixed at
 * resident by the service; the password is generated by the server, so there
 * is nothing for the caller to choose and no field through which a weak one
 * could be smuggled in.
 *
 * `phone` is required — the office rings the resident, and an account with no
 * number is an account nobody can reach. `citizenship` is a closed list
 * (`App\Enums\Citizenship`), which is what makes it a dropdown rather than a
 * free string spelled four ways.
 */
final class StoreResidentAccountRequest extends FormRequest
{
    public function authorize(): bool
    {
        $building = $this->route('building');

        return $building instanceof Building
            && $this->user()?->can('issueResidentAccount', $building) === true;
    }

    /**
     * @return array<string, list<mixed>>
     */
    public function rules(): array
    {
        return [
            'full_name' => ['required', 'string', 'max:255'],
            // The address the account signs in with, so it is the one field
            // that cannot be left out or duplicated.
            'email' => ['required', 'email', 'max:255', Rule::unique('users', 'email')],
            'phone' => ['required', 'string', 'max:32'],
            'citizenship' => ['required', Rule::enum(Citizenship::class)],
        ];
    }

    /**
     * @return array<string, mixed>
     */
    public function payload(): array
    {
        return $this->safe()->only(['full_name', 'email', 'phone', 'citizenship']);
    }
}
